# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache NPM
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/Package.resolved') }}

    - name: Cache Composer
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4          
        extensions: dom, curl, libxml, pdo_mysql, bcmath, exif, mbstring, mcrypt, intl, zip
        tools: pecl, composer, phpunit
        coverage: pcov
    
    - name: Execute tests
      run: vendor/bin/phpunit --verbose
